import {interviewPanel,mountInterviews,interviewBusy,disposeInterviews} from './interviews.js';
import QRCode from 'qrcode';
import jsQR from 'jsqr';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const paths={user:'M20 21a8 8 0 0 0-16 0 M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8',briefcase:'M9 7V4h6v3 M3 7h18v14H3z M3 12h18 M10 12v3h4v-3',qr:'M3 3h6v6H3z M15 3h6v6h-6z M3 15h6v6H3z M15 15h3v3h3v3h-6v-3 M21 12h-3 M12 3v6 M12 12h3v3h-3v6',camera:'M3 7h4l2-3h6l2 3h4v14H3z M16 14a4 4 0 1 0-8 0 4 4 0 0 0 8 0',upload:'M12 16V3 M7 8l5-5 5 5 M4 15v6h16v-6',download:'M12 3v13 M7 11l5 5 5-5 M4 16v5h16v-5',mic:'M9 3h6v11a3 3 0 0 1-6 0z M5 11v3a7 7 0 0 0 14 0v-3 M12 21v-3 M9 21h6',lock:'M7 10V7a5 5 0 0 1 10 0v3 M4 10h16v11H4z M12 14v3',shield:'M12 2l9 4v6c0 5-5 8-9 10-4-2-9-5-9-10V6z M8 12l3 3 5-6',ticket:'M3 5h18v5a2 2 0 0 0 0 4v5H3v-5a2 2 0 0 0 0-4z M15 5v3 M15 11v2 M15 16v3',route:'M5 6h14v5H5v6h14 M8 6a3 3 0 1 0-6 0 3 3 0 0 0 6 0 M22 17a3 3 0 1 0-6 0 3 3 0 0 0 6 0',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M13 7a4 4 0 1 0-8 0 4 4 0 0 0 8 0 M17 4a4 4 0 0 1 0 8 M22 21v-2a4 4 0 0 0-3-4',columns:'M3 3h5v18H3z M10 3h5v14h-5z M17 3h4v18h-4z',message:'M21 3H3v14h5v4l5-4h8z M7 8h10 M7 12h6',sparkles:'M12 3l2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z M20 2v4 M18 4h4',search:'M17 10a7 7 0 1 0-14 0 7 7 0 0 0 14 0 M15 15l6 6',refresh:'M20 7a9 9 0 0 0-15-2 M3 3v6h6 M4 17a9 9 0 0 0 15 2 M21 21v-6h-6',check:'M5 12l4 4L20 5',x:'M6 6l12 12 M18 6L6 18','arrow-right':'M4 12h16 M14 6l6 6-6 6','arrow-up-right':'M5 19L19 5 M5 5h14v14','log-out':'M9 3H3v18h6 M12 12h9 M17 8l4 4-4 4',file:'M4 2h10l6 6v14H4z M14 2v6h6 M8 13h8 M8 17h8',clock:'M12 8v5l3 2 M22 12a10 10 0 1 0-20 0 10 10 0 0 0 20 0'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.file}"/></svg>`;
function icons(root=document){root.querySelectorAll('[data-icon]').forEach(e=>{e.outerHTML=icon(e.dataset.icon)});}
icons();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={step:0,event:false,candidates:[],removedCandidates:[],selected:null,detailTab:'overview',workspace:'queue',resume:null,resumeText:'',resumeImages:[],interviewer:false,started:Date.now(),session:crypto.randomUUID(),recording:null};
const form=$('#intake-form'),field=n=>form.elements.namedItem(n);
async function api(path,options={}){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),65000);try{const r=await fetch(path,{...options,headers:{'content-type':'application/json',...(options.headers||{})},signal:controller.signal});const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw Error(`The service did not respond correctly (${r.status}). Please try again.`)}if(!r.ok)throw Error(data.error||`Request failed (${r.status}).`);return data;}catch(e){if(e.name==='AbortError')throw Error('The request timed out. Your entered details are still here. Try again.');throw e}finally{clearTimeout(timeout)}}
const post=(path,data)=>api(path,{method:'POST',body:JSON.stringify(data)});
function toast(text){$('#toast').textContent=text;$('#toast').classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.add('hidden'),5000);}
function showError(e){$('#form-error').textContent=e.message||e;$('#form-error').focus();}
async function busy(button,label,fn){const old=button.innerHTML;button.disabled=true;button.textContent=label;try{return await fn()}finally{button.disabled=false;button.innerHTML=old;}}
function step(n){state.step=n;$('#form-error').textContent='';$$('[data-step]').forEach(e=>e.classList.toggle('hidden',Number(e.dataset.step)!==n));$$('[data-step-marker]').forEach(e=>{const i=Number(e.dataset.stepMarker);e.classList.toggle('active',i===n);e.classList.toggle('done',i<n);e.setAttribute('aria-current',i===n?'step':'false')});$('#step-counter').textContent=`STEP ${String(n+1).padStart(2,'0')} OF 04`;if(innerWidth<761)$('.candidate-content').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'start'});}
$$('[data-back]').forEach(b=>b.onclick=()=>step(Math.max(0,state.step-1)));
async function route(){if(interviewBusy()){if(location.hash!=='#dashboard'){location.hash='#dashboard';toast('Stop the interview and finish saving before leaving the workspace.');}return;}const dashboard=location.hash==='#dashboard';$('#intake').classList.toggle('hidden',dashboard);$('#dashboard').classList.toggle('hidden',!dashboard);$$('[data-route]').forEach(a=>a.setAttribute('aria-current',a.dataset.route===(dashboard?'dashboard':'intake')?'page':'false'));closeMedia();if(dashboard)await checkInterviewer();}
addEventListener('hashchange',route);
$('#workspace-date').textContent=new Date().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'});
async function readiness(){try{const h=await api('/api/health');if(!h.ok){$('#service-banner').textContent='The organizer is finishing setup. You can prepare your details, but check-in will open once the database is connected.';$('#service-banner').classList.remove('hidden')}else if(!h.aiConfigured){$('#service-banner').textContent='Check-in is available. Resume extraction and voice transcription will open once the organizer enables AI.';$('#service-banner').classList.remove('hidden')}else $('#service-banner').classList.add('hidden');}catch{$('#service-banner').textContent='Connection unavailable. Please reconnect before checking in.';$('#service-banner').classList.remove('hidden')}}
$('#join-event').onclick=async()=>{try{await busy($('#join-event'),'Joining event…',async()=>{const code=field('eventCode').value.trim();if(!/^\d{5}$/.test(code))throw Error('Enter your five-digit event code.');await api(`/api/event?code=${encodeURIComponent(code)}`);state.event=true;step(1)});}catch(e){showError(e)}};
$('#save-profile').onclick=()=>{for(const n of ['firstName','lastName','email']){if(!field(n).reportValidity())return;}step(2)};
$('#review-checkin').onclick=()=>{for(const n of ['university','degreeProgram','major','graduationDate','desiredFunction']){if(!field(n).reportValidity())return;}state.resumeText=$('#resume-text').value;renderReview();step(3)};
function renderReview(){const d=Object.fromEntries(new FormData(form));$('#checkin-review').innerHTML=`<h3>${esc(d.preferredName||d.firstName)} ${esc(d.lastName)}</h3><p>${esc(d.email)}</p><dl><dt>Education</dt><dd>${esc(d.major)} · ${esc(d.degreeProgram)}<br>${esc(d.university)}</dd><dt>Graduation</dt><dd>${esc(d.graduationDate)}</dd><dt>Career interest</dt><dd>${esc(d.desiredFunction)}</dd><dt>Resume</dt><dd>${esc(state.resume?.name||'No resume attached')}</dd><dt>Skills</dt><dd>${esc(d.relevantSkills||'Not supplied')}</dd><dt>Event</dt><dd>J.B. Hunt Career Fair · 12345</dd><dt>AI consent</dt><dd>${d.aiConsent?'Opted in to Groq processing':'Not opted in'}</dd></dl>`;}
form.onsubmit=async e=>{e.preventDefault();if(state.step!==3)return;if(!$('#data-consent').reportValidity())return;try{await busy(form.querySelector('[type=submit]'),'Completing check-in…',async()=>{const d=Object.fromEntries(new FormData(form));delete d.resume;const split=v=>String(v||'').split(/[,;]/).map(x=>x.trim()).filter(Boolean);const resume=state.resume?{name:state.resume.name,type:state.resume.type,base64:await toBase64(state.resume)}:null;const result=await post('/api/candidates',{...d,technicalInterests:split(d.technicalInterests),preferredLocations:split(d.preferredLocations),relevantSkills:split(d.relevantSkills),resume,resumeText:$('#resume-text').value,sessionId:state.session,durationMs:Date.now()-state.started});confirmation(result.confirmationCode)});}catch(e){showError(e)}};
function confirmation(code){form.classList.add('hidden');$('.stepper').classList.add('hidden');$('#confirmation').classList.remove('hidden');$('#code').textContent=code;$('#step-counter').textContent='CHECK-IN COMPLETE';$('#confirmation').focus();}
$('#another').onclick=()=>{resetCandidate();toast('Ready for the next candidate.');};
function resetCandidate(){form.reset();state.session=crypto.randomUUID();state.resume=null;state.resumeText='';state.resumeImages=[];state.event=false;state.started=Date.now();$('#resume-text').value='';$('#resume-preview').classList.add('hidden');$('#parse-resume').classList.add('hidden');$('#intro-audio').classList.add('hidden');$('#intro-recording').textContent='';$('#resume-status').textContent='';$('#confirmation').classList.add('hidden');form.classList.remove('hidden');$('.stepper').classList.remove('hidden');if($('#intro-audio').dataset.objectUrl){URL.revokeObjectURL($('#intro-audio').dataset.objectUrl);delete $('#intro-audio').dataset.objectUrl;}$('#intro-audio').removeAttribute('src');$('#resume-preview').innerHTML='';$('#code').textContent='';step(0);}
function toBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('The file could not be read.'));reader.readAsDataURL(file)})}
async function imageCanvas(file){const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,1800/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return canvas;}finally{URL.revokeObjectURL(url)}}
const blobFromCanvas=canvas=>new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.85));
async function prepareResume(file){$('#resume-status').textContent='Preparing your resume…';$('#parse-resume').classList.add('hidden');try{let selected=file;state.resumeImages=[];if(file.type.startsWith('image/')){const canvas=await imageCanvas(file);const blob=await blobFromCanvas(canvas);selected=new File([blob],file.name.replace(/\.[^.]+$/,'.jpg'),{type:'image/jpeg'});state.resumeImages=[canvas.toDataURL('image/jpeg',.85)];}if(selected.size>3e6)throw Error('Use a resume under 3 MB. Images are resized automatically.');if(!/\.(pdf|txt|jpe?g|png|webp)$/i.test(selected.name))throw Error('Choose a PDF, text, JPEG, PNG, or WebP file.');let text='';if(/\.txt$/i.test(selected.name))text=(await selected.text()).slice(0,20000);if(/\.pdf$/i.test(selected.name)){const pdfjs=await import('/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='/pdf.worker.mjs';const pdf=await pdfjs.getDocument({data:new Uint8Array(await selected.arrayBuffer())}).promise;try{if(pdf.numPages>30)throw Error('Use a resume of 30 pages or fewer.');for(let i=1;i<=pdf.numPages&&text.length<20000;i++){const page=await pdf.getPage(i),content=await page.getTextContent();text+=content.items.map(item=>item.str||'').join(' ')+'\n';}if(text.trim().length<50){if(pdf.numPages>3)throw Error('Scanned PDFs can have up to 3 pages. Upload a shorter resume or a searchable PDF.');text='';for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),base=page.getViewport({scale:1}),vp=page.getViewport({scale:Math.min(2,1800/Math.max(base.width,base.height))}),canvas=document.createElement('canvas');canvas.width=vp.width;canvas.height=vp.height;await page.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise;state.resumeImages.push(canvas.toDataURL('image/jpeg',.8));}}}finally{await pdf.destroy()}}
state.resume=selected;state.resumeText=text.trim().slice(0,20000);$('#resume-text').value=state.resumeText;const image=state.resumeImages[0];$('#resume-preview').innerHTML=`${image?`<img src="${image}" alt="Resume preview">`:icon('file')}<div><strong>${esc(selected.name)}</strong><small>${(selected.size/1024).toFixed(0)} KB · ${state.resumeText?'Readable text extracted':'Ready for image extraction'}</small></div><button type="button" class="icon-button" id="remove-resume" aria-label="Remove resume">${icon('x')}</button>`;$('#resume-preview').classList.remove('hidden');$('#parse-resume').classList.remove('hidden');$('#resume-status').textContent=state.resumeText?'Resume attached. Extract details with Groq or review the text below.':'Resume attached. Enable AI consent to extract this image with Groq.';$('#remove-resume').onclick=()=>{state.resume=null;state.resumeText='';state.resumeImages=[];$('#resume').value='';$('#resume-text').value='';$('#resume-preview').classList.add('hidden');$('#parse-resume').classList.add('hidden');$('#resume-status').textContent='Resume removed.';};}catch(e){state.resume=null;state.resumeImages=[];$('#resume-preview').classList.add('hidden');$('#resume-status').textContent=e.message;}}
$('#upload-resume').onclick=()=>$('#resume').click();$('#resume').onchange=()=>{if($('#resume').files[0])prepareResume($('#resume').files[0])};$('#resume-camera').onchange=()=>{if($('#resume-camera').files[0])prepareResume($('#resume-camera').files[0])};
$('#parse-resume').onclick=async()=>{if(!$('#ai-consent').checked){$('#resume-status').textContent='Please enable AI consent above before sending your resume to Groq.';return;}try{await busy($('#parse-resume'),'Reading your resume…',async()=>{const r=await post('/api/resume/parse',{images:state.resumeImages,text:$('#resume-text').value,aiConsent:true,eventCode:field('eventCode').value});state.resumeText=r.resumeText;$('#resume-text').value=r.resumeText;for(const [name,value]of Object.entries(r.fields||{})){const input=field(name);if(!input||input.value||!value)continue;const v=Array.isArray(value)?value.join(', '):String(value);if(input.tagName==='SELECT'&&!Array.from(input.options).some(o=>o.value===v)){input.add(new Option(v,v))}input.value=v;}$('#resume-text-details').open=true;$('#resume-status').textContent='Extraction complete. Review the text and your details before submitting.'+(r.warnings.length?' '+r.warnings.join(' '):'');toast('Resume extracted. Please verify the details.');});}catch(e){$('#resume-status').textContent=e.message}};
let mediaStream=null,qrFrame=null;
function closeMedia(){if(mediaStream){mediaStream.getTracks().forEach(t=>t.stop());mediaStream=null;}if(qrFrame)cancelAnimationFrame(qrFrame);qrFrame=null;$('#qr-video').srcObject=null;$('#resume-video').srcObject=null;}
async function camera(video){closeMedia();if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera access needs HTTPS and a supported browser. Use your phone camera or upload an image instead.');mediaStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});video.srcObject=mediaStream;await video.play();}
function mediaError(e){return e.name==='NotAllowedError'?'Camera permission was declined. Allow camera access in your browser settings, or use an image instead.':e.name==='NotFoundError'?'No camera was found. Upload an image instead.':e.message;}
$('#scan-resume').onclick=async()=>{$('#camera-dialog').showModal();$('#camera-status').textContent='Opening camera…';$('#take-photo').disabled=true;try{await camera($('#resume-video'));$('#camera-status').textContent='Keep the full resume page in view.';$('#take-photo').disabled=false}catch(e){$('#camera-status').textContent=mediaError(e)}};
$('#native-camera').onclick=()=>{$('#camera-dialog').close();closeMedia();$('#resume-camera').click()};
$('#take-photo').onclick=async()=>{const video=$('#resume-video');if(!video.videoWidth){$('#camera-status').textContent='The camera is not ready yet.';return;}const canvas=document.createElement('canvas'),scale=Math.min(1,1800/video.videoWidth);canvas.width=video.videoWidth*scale;canvas.height=video.videoHeight*scale;canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);const blob=await blobFromCanvas(canvas);$('#camera-dialog').close();closeMedia();await prepareResume(new File([blob],'resume-scan.jpg',{type:'image/jpeg'}));};
function qrCode(text){if(String(text).trim()==='12345')return'12345';try{const u=new URL(text);return u.searchParams.get('event')==='12345'||u.searchParams.get('code')==='12345'?'12345':null}catch{return null}}
function acceptQR(text){const code=qrCode(text);if(!code){$('#qr-status').textContent='This QR code is not a TalentIQ event code. Use the code at our booth.';return false}field('eventCode').value=code;$('#qr-dialog').close();closeMedia();toast('Event code scanned. Select Join the event.');return true;}
$('#scan-qr').onclick=async()=>{$('#qr-dialog').showModal();$('#qr-status').textContent='Opening camera…';try{await camera($('#qr-video'));$('#qr-status').textContent='Align the code inside the frame.';const canvas=document.createElement('canvas');let last=0;function detect(t){if(!mediaStream||!$('#qr-dialog').open)return;const video=$('#qr-video');if(t-last>160&&video.videoWidth){last=t;canvas.width=640;canvas.height=video.videoHeight/video.videoWidth*640;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(video,0,0,canvas.width,canvas.height);const data=ctx.getImageData(0,0,canvas.width,canvas.height),code=jsQR(data.data,data.width,data.height,{inversionAttempts:'attemptBoth'});if(code&&acceptQR(code.data))return;}qrFrame=requestAnimationFrame(detect)}qrFrame=requestAnimationFrame(detect);}catch(e){$('#qr-status').textContent=mediaError(e)}};
$('#qr-file-button').onclick=()=>$('#qr-image').click();$('#qr-image').onchange=async()=>{const file=$('#qr-image').files[0];if(!file)return;try{const canvas=await imageCanvas(file),data=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height),code=jsQR(data.data,data.width,data.height,{inversionAttempts:'attemptBoth'});if(!code)throw Error('No QR code found. Try a clearer image or enter 12345.');acceptQR(code.data)}catch(e){$('#qr-status').textContent=e.message}finally{$('#qr-image').value=''}};
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.addEventListener('close',()=>{if(['qr-dialog','camera-dialog'].includes(d.id))closeMedia();if(d.id==='detail-dialog')disposeInterviews();}));
$('#event-qr').onclick=async()=>{$('#event-dialog').showModal();const url=`${location.origin}/?event=12345#intake`;try{await QRCode.toCanvas($('#event-qr-canvas'),url,{width:440,margin:2,color:{dark:'#263020',light:'#ffffff'},errorCorrectionLevel:'M'});}catch(e){toast(e.message)}};
$('#download-qr').onclick=()=>{const a=document.createElement('a');a.href=$('#event-qr-canvas').toDataURL('image/png');a.download='TalentIQ-event-12345-QR.png';a.click();};
async function record(kind,button,status,audio,consent,target,candidateId){
  if(state.recording){if(state.recording.kind===kind)state.recording.stop();else toast('Finish the other recording first.');return;}
  if(!consent.checked){status.textContent=kind==='interview'?'Confirm permission from everyone being recorded first.':'Confirm voice transcription consent first.';return;}
  if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){status.textContent='Recording is unavailable in this browser. Type your notes instead.';return;}
  let stream;try{stream=await navigator.mediaDevices.getUserMedia({audio:true});}catch(e){status.textContent=e.name==='NotAllowedError'?'Microphone permission was declined. Allow it in browser settings or type your notes.':'A microphone could not be opened.';return;}
  const formats=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'],format=formats.find(x=>MediaRecorder.isTypeSupported(x));const recorder=new MediaRecorder(stream,format?{mimeType:format}:{}),chunks=[];let size=0,stopped=false;
  const old=button.innerHTML,started=Date.now();button.innerHTML=`${icon('mic')} Stop recording`;status.classList.add('recording');
  const timer=setInterval(()=>status.textContent=`Recording · ${Math.floor((Date.now()-started)/1000)}s / 60s`,1000);
  const cutoff=setTimeout(()=>stop(),60000);
  function stop(){if(stopped)return;stopped=true;clearTimeout(cutoff);clearInterval(timer);if(recorder.state!=='inactive')recorder.stop();stream.getTracks().forEach(t=>t.stop());}
  state.recording={kind,stop};
  recorder.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);size+=e.data.size;if(size>2800000)stop();}};
  recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());state.recording=null;button.innerHTML=old;status.classList.remove('recording');const mime=(recorder.mimeType||'audio/webm').split(';')[0],blob=new Blob(chunks,{type:mime});if(audio.dataset.objectUrl)URL.revokeObjectURL(audio.dataset.objectUrl);audio.src=URL.createObjectURL(blob);audio.dataset.objectUrl=audio.src;audio.classList.remove('hidden');if(blob.size>3e6){status.textContent='Recording is too large to transcribe. Record a shorter segment.';return;}let data={base64:await toBase64(blob),mime,consent:true,candidateId,eventCode:field('eventCode').value};async function send(){status.textContent='Transcribing with Groq…';button.disabled=true;try{const r=await post('/api/transcribe',data);target.value=[target.value,r.text].filter(Boolean).join('\n\n');status.textContent='Transcript added below. Review it, then save your notes.';toast('Transcript ready for review.');data=null;}catch(e){status.textContent=e.message;const retry=document.createElement('button');retry.className='text-button';retry.type='button';retry.textContent='Retry transcription';retry.onclick=()=>{retry.remove();send()};status.append(document.createElement('br'),retry);}finally{button.disabled=false}}await send();};
  recorder.onerror=()=>{stop();status.textContent='Recording stopped unexpectedly. Try again or type your notes.'};
  recorder.start(1000);status.textContent='Recording · speak naturally.';
}
$('#record-intro').onclick=()=>record('intro',$('#record-intro'),$('#intro-recording'),$('#intro-audio'),$('#candidate-voice-consent'),$('#project-experience'));
async function checkInterviewer(){state.interviewer=false;$('#recruiter-access').textContent='';$('#authorized-workspace').classList.add('hidden');$('#auth-container').classList.remove('hidden');$('#export').classList.add('hidden');$('#signout').classList.add('hidden');try{const r=await api('/api/recruiter-session');state.interviewer=r.authorized;$('#show-setup').classList.toggle('hidden',!r.setupAvailable);if(r.authorized){$('#auth-container').classList.add('hidden');$('#authorized-workspace').classList.remove('hidden');$('#export').classList.remove('hidden');$('#signout').classList.remove('hidden');await loadCandidates();}}catch(e){$('#recruiter-access').textContent=e.message;}}
$('#show-setup').onclick=e=>{e.preventDefault();$('#login-form').classList.add('hidden');$('#setup-form').classList.remove('hidden')};$('#back-login').onclick=()=>{$('#setup-form').classList.add('hidden');$('#login-form').classList.remove('hidden')};
for(const id of ['login','setup'])$(`#${id}-form`).onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await busy(f.querySelector('.primary'),'Opening workspace…',async()=>{await post(`/api/auth/${id}`,Object.fromEntries(new FormData(f)));f.reset();await checkInterviewer();});}catch(x){$(`#${id}-error`).textContent=x.message}};
$('#signout').onclick=async()=>{if(interviewBusy()){toast('Stop the interview and finish saving before signing out.');return;}try{await post('/api/auth/logout',{});state.candidates=[];state.removedCandidates=[];state.selected=null;$('#detail-dialog').close();await checkInterviewer();toast('You’re signed out.');}catch(e){toast(e.message)}};
async function loadCandidates(){if(!state.interviewer)return;$('#sync').textContent='Refreshing queue…';try{const [r,removed]=await Promise.all([api('/api/candidates?event=12345'),api('/api/candidates?event=12345&removed=1')]);state.candidates=r.candidates;state.removedCandidates=removed.candidates;renderQueue();$('#sync').textContent=`Updated ${new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})} · ${r.candidates.length} check-ins`;if(state.selected){const fresh=[...state.candidates,...state.removedCandidates].find(c=>c.id===state.selected.id);if(fresh){state.selected=fresh;}}}catch(e){$('#sync').textContent=e.message;toast(e.message)}}
$('#refresh').onclick=()=>state.interviewer?loadCandidates():checkInterviewer();$('#search').oninput=renderQueue;$('#status').onchange=renderQueue;$('#checkin-view').onchange=renderQueue;
$$('[data-workspace]').forEach(b=>b.onclick=()=>{state.workspace=b.dataset.workspace;$$('[data-workspace]').forEach(x=>x.classList.toggle('active',x===b));$('#queue-view').classList.toggle('hidden',state.workspace!=='queue');$('#pipeline-view').classList.toggle('hidden',state.workspace!=='pipeline');renderQueue();});
const statuses=['New','Reviewed','Follow-Up','Interview Requested','Closed'];
const name=c=>`${c.preferredName||c.firstName} ${c.lastName}`;
const avatar=(c,i=0)=>`<span class="avatar tone-${i%4}">${esc((c.firstName?.[0]||'')+(c.lastName?.[0]||''))}</span>`;
function renderQueue(){const removed=$('#checkin-view').value==='removed',all=state.candidates,display=removed?state.removedCandidates:all;$('#queue-title').childNodes[0].textContent=removed?'Removed check-ins ':state.workspace==='queue'?'Candidate queue ':'Candidate pipeline ';$('#stat-total').textContent=all.length;$('#sidebar-count').textContent=all.length;$('#stat-new').textContent=all.filter(c=>c.recordStatus==='New').length;$('#stat-followup').textContent=all.filter(c=>c.recordStatus==='Follow-Up'||c.recordStatus==='Interview Requested').length;$('#stat-briefs').textContent=all.filter(c=>c.summary).length;const q=$('#search').value.toLowerCase().trim(),status=$('#status').value;const rows=display.filter(c=>(!status||c.recordStatus===status)&&(!q||[name(c),c.email,c.university,c.major,...c.relevantSkills].join(' ').toLowerCase().includes(q)));$('#count').textContent=rows.length;
if(!rows.length)$('#queue-view').innerHTML=`<div class="empty-state">${icon('users')}<h3>${display.length?'No matching candidates.':removed?'No removed check-ins.':'Your next conversation is on its way.'}</h3><p>${display.length?'Try a different search or stage.':removed?'Removed check-ins will appear here for review or restoration.':'Share the event QR code or code 12345 at your booth. Check-ins will appear here.'}</p>${!removed&&!all.length?'<button class="secondary" id="empty-qr">Show event QR code</button>':''}</div>`;
else $('#queue-view').innerHTML=`<table><thead><tr><th>Candidate</th><th class="school-column">Education</th><th class="skills-column">Focus / skills</th><th>Stage</th><th class="brief-column">Interview brief</th><th aria-label="Open candidate"></th></tr></thead><tbody>${rows.map((c,i)=>`<tr><td><div class="person-cell">${avatar(c,i)}<div><a href="#dashboard" class="person-name" data-open="${esc(c.id)}">${esc(name(c))}</a><span class="person-email">${esc(c.email)}</span></div></div></td><td class="school-column">${esc(c.university)}<span class="cell-small">${esc(c.major)}</span></td><td class="skills-column">${esc(c.desiredFunction)}<div>${c.relevantSkills.slice(0,2).map(s=>`<span class="tag">${esc(s)}</span>`).join('')}</div></td><td><span class="badge ${esc(c.recordStatus)}">${esc(c.recordStatus)}</span></td><td class="brief-column">${c.summary?`<span class="badge">${c.approvalStatus==='Approved'?'Reviewed':'Draft ready'}</span>`:`<span class="cell-small">${c.aiConsent?'Not generated':'AI not enabled'}</span>`}</td><td><button class="icon-button" aria-label="Open ${esc(name(c))}" data-open="${esc(c.id)}">${icon('arrow-up-right')}</button></td></tr>`).join('')}</tbody></table>`;
$('#pipeline-view').innerHTML=statuses.map(s=>{const cards=rows.filter(c=>c.recordStatus===s);return`<section class="pipeline-column"><h3>${esc(s)}<span>${cards.length}</span></h3>${cards.length?cards.map((c,i)=>`<button class="pipeline-card" data-open="${esc(c.id)}">${avatar(c,i)}<span class="person-name">${esc(name(c))}</span><p>${esc(c.university)}</p><span class="tag">${esc(c.desiredFunction)}</span></button>`).join(''):'<p>No candidates in this stage yet.</p>'}</section>`}).join('');
if($('#empty-qr'))$('#empty-qr').onclick=()=>$('#event-qr').click();$$('[data-open]').forEach(b=>b.onclick=e=>{e.preventDefault();openCandidate(b.dataset.open)});
}
function openCandidate(id){state.selected=[...state.candidates,...state.removedCandidates].find(c=>c.id===id);if(!state.selected)return;state.detailTab='overview';renderDetail();$('#detail-dialog').showModal();}
function stashNotes(){if(!state.selected)return;const f=$('#notes-form');if(f)state.selected.observations={...state.selected.observations,...Object.fromEntries(new FormData(f))};}
function renderDetail(){disposeInterviews();const c=state.selected;if(!c)return;const brief=c.summary,questions=brief?.interviewQuestions||[];let main='';
if(state.detailTab==='overview')main=`<section class="detail-section"><h3>${icon('file')}Candidate at a glance</h3><dl><dt>University</dt><dd>${esc(c.university)}</dd><dt>Degree / major</dt><dd>${esc(c.degreeProgram)} · ${esc(c.major)}</dd><dt>Graduation</dt><dd>${esc(c.graduationDate)}</dd><dt>Career interest</dt><dd>${esc(c.desiredFunction)}</dd><dt>Locations</dt><dd>${esc(c.preferredLocations.join(', ')||'Not supplied')}</dd><dt>Phone</dt><dd>${esc(c.phone||'Not supplied')}</dd></dl><h4>Skills & interests</h4>${[...c.relevantSkills,...c.technicalInterests].map(s=>`<span class="tag">${esc(s)}</span>`).join('')||'<p>No skills supplied yet.</p>'}<h4>Project experience</h4><p>${esc(c.projectExperience||'Not supplied')}</p></section><section class="detail-section"><h3>${icon('sparkles')}Interview brief</h3><div class="summary-callout">${!c.aiConsent?'This candidate has not opted in to external AI processing. Capture your conversation in Notes.':'AI drafts summarize supplied evidence. Verify the source before using a statement or question.'}</div>${brief?`<ul class="summary-list">${brief.statements.map(s=>`<li>${esc(s.text)}<br>${s.citations.map(x=>`<span class="source-chip">${esc(x)}</span>`).join('')}</li>`).join('')}</ul><p>Model: ${esc(brief.model)} · ${esc(c.approvalStatus)} draft</p>`:'<p>Generate a brief to prepare questions tailored to the candidate’s resume and projects.</p>'}<button class="primary" id="generate" ${!c.aiConsent?'disabled':''}>${icon('sparkles')}${brief?'Regenerate brief':'Generate interview brief'}</button>${brief?'<button class="secondary" id="approve-brief">Mark brief reviewed</button>':''}<p id="summary-error" class="detail-status" role="status"></p></section>`;
if(state.detailTab==='questions')main=`<section class="detail-section"><h3>${icon('message')}A stronger first conversation</h3><div class="summary-callout">Suggested questions reference this candidate’s professional experience. Use your judgment and review the source.</div>${questions.length?`<div class="question-list">${questions.map(q=>`<article class="question-item"><div><p>${esc(q.text)}</p>${q.citations.map(x=>`<span class="source-chip">${esc(x)}</span>`).join('')}</div></article>`).join('')}</div>`:'<div class="empty-state"><h3>Start with their story.</h3><p>Generate an interview brief from the Overview tab to see source-linked questions here.</p></div>'}</section>`;
if(state.detailTab==='notes')main=`<form id="notes-form" class="detail-section"><h3>${icon('mic')}Capture the conversation</h3>${interviewPanel(c)}<label>Interviewer name<input name="recruiterName" value="${esc(c.observations.recruiterName)}"></label><label>Conversation notes<textarea name="conversationNotes" id="conversation-notes" rows="7" placeholder="Projects discussed, answers, and evidence…">${esc(c.observations.conversationNotes)}</textarea></label><label>Areas discussed<textarea name="areasDiscussed" rows="2">${esc(c.observations.areasDiscussed)}</textarea></label><label>Follow-up questions<textarea name="followUpQuestions" rows="2">${esc(c.observations.followUpQuestions)}</textarea></label><label>Candidate’s questions<textarea name="candidateQuestions" rows="2">${esc(c.observations.candidateQuestions)}</textarea></label><label>Next steps (your decision)<textarea name="recommendedNextSteps" rows="2">${esc(c.observations.recommendedNextSteps)}</textarea></label><button class="primary" type="submit">Save conversation notes ${icon('check')}</button><p id="notes-status" class="detail-status" role="status"></p></form>`;
$('#detail').innerHTML=`<div class="detail-header"><div class="detail-person">${avatar(c)}<div><h2>${esc(name(c))}</h2><p>${esc(c.desiredFunction)} · ${esc(c.university)}</p></div></div><button class="icon-button" id="close-detail" aria-label="Close candidate">${icon('x')}</button></div><div class="detail-tabs">${['overview','questions','notes'].map(t=>`<button data-detail-tab="${t}" class="${state.detailTab===t?'active':''}" aria-pressed="${state.detailTab===t}">${t[0].toUpperCase()+t.slice(1)}${t==='questions'&&questions.length?' ('+questions.length+')':''}</button>`).join('')}</div><div class="detail-body"><div>${main}</div><aside class="detail-side"><section class="detail-section"><h3>Keep things moving.</h3><span class="badge ${esc(c.recordStatus)}">${esc(c.recordStatus)}</span><label>Candidate stage<select id="candidate-stage">${statuses.map(s=>`<option ${s===c.recordStatus?'selected':''}>${s}</option>`).join('')}</select></label><p>Stage changes are made by you.</p><div id="stage-status" class="detail-status" role="status"></div></section><section class="detail-section"><h3>${icon('file')}Resume source</h3>${c.resumeName?`<p>${esc(c.resumeName)}</p>${c.removedAt?'<p>Restore this check-in to download the retained resume.</p>':`<a class="button secondary full" href="/api/candidates/${encodeURIComponent(c.id)}/resume">${icon('download')}Download original</a>`}`:'<p>No resume attached.</p>'}${c.resumeText?`<details class="optional-fields"><summary>View resume text</summary><div class="source-text">${esc(c.resumeText)}</div></details>`:''}</section><section class="detail-section"><h3>${icon('shield')}Consent & context</h3><p>${c.aiConsent?'Candidate opted in to Groq processing.':'Candidate did not opt in to AI.'}</p><p>Event ${esc(c.eventCode)}</p><p>Checked in ${esc(new Date(c.createdAt).toLocaleString())}</p><p>Check-in code ${esc(c.id.slice(0,8).toUpperCase())}</p></section><section class="detail-section checkin-actions"><h3>${c.removedAt?'Removed check-in':'Manage check-in'}</h3><p>${c.removedAt?'This check-in is outside the active queue. Restore it to resume the conversation.':'Remove duplicate or unwanted check-ins from your active queue.'}</p><button type="button" class="${c.removedAt?'secondary':'danger'} full" id="manage-checkin">${icon(c.removedAt?'refresh':'x')}${c.removedAt?'Restore check-in':'Remove check-in'}</button><p id="manage-error" class="detail-status" role="alert"></p></section></aside></div>`;
if(c.removedAt)$('#detail').querySelectorAll('#generate,#approve-brief,#candidate-stage,#notes-form button,#notes-form input,#notes-form textarea').forEach(el=>el.disabled=true);
$('#manage-checkin').onclick=async()=>{
  if(state.recording||interviewBusy()){toast('Finish recording and saving before changing this check-in.');return;}
  if(c.removedAt){try{await busy($('#manage-checkin'),'Restoring…',async()=>{await post(`/api/candidates/${encodeURIComponent(c.id)}/restore`,{});$('#detail-dialog').close();state.selected=null;await loadCandidates();toast('Check-in restored to the active queue.');});}catch(e){$('#manage-error').textContent=e.message}}
  else{$('#remove-description').textContent=`Remove ${name(c)} (${c.email}) from the interviewer queue?`;$('#remove-error').textContent='';$('#remove-dialog').showModal();}
};
$('#close-detail').onclick=()=>{if(interviewBusy()){toast('Stop the interview and finish saving before closing.');return;}stashNotes();$('#detail-dialog').close()};$$('[data-detail-tab]').forEach(b=>b.onclick=()=>{if(state.recording||interviewBusy()){toast('Finish recording and saving before switching tabs.');return;}stashNotes();state.detailTab=b.dataset.detailTab;renderDetail();});
$('#candidate-stage').onchange=async e=>{const value=e.target.value;try{await api(`/api/candidates/${c.id}`,{method:'PATCH',body:JSON.stringify({recordStatus:value})});c.recordStatus=value;$('#stage-status').textContent='Stage saved.';renderQueue();}catch(x){e.target.value=c.recordStatus;$('#stage-status').textContent=x.message}};
if($('#generate'))$('#generate').onclick=async()=>{try{await busy($('#generate'),'Preparing your brief…',async()=>{const r=await post(`/api/candidates/${c.id}/summary`,{});c.summary=r.summary;c.approvalStatus='Pending';renderQueue();renderDetail();toast('Draft ready. Verify the brief and suggested questions.');});}catch(x){$('#summary-error').textContent=x.message}};
if($('#approve-brief'))$('#approve-brief').onclick=async()=>{try{await busy($('#approve-brief'),'Saving review…',async()=>{const r=await post(`/api/candidates/${c.id}/review`,{action:'Approved'});Object.assign(c,r.candidate);renderQueue();renderDetail();toast('Interview brief marked as reviewed.');});}catch(x){$('#summary-error').textContent=x.message}};
if($('#notes-form')){$('#notes-form').onsubmit=async e=>{e.preventDefault();if(state.recording||interviewBusy()){$('#notes-status').textContent='Finish the recording and review the transcript before saving notes.';return;}stashNotes();try{await busy(e.currentTarget.querySelector('[type=submit]'),'Saving notes…',async()=>{const r=await api(`/api/candidates/${c.id}`,{method:'PATCH',body:JSON.stringify({observations:c.observations})});Object.assign(c,r.candidate);$('#notes-status').textContent='Conversation notes saved.';toast('Notes saved.');});}catch(x){$('#notes-status').textContent=x.message}};mountInterviews(c,{api,post,esc,toast,onAddNotes:text=>{$('#conversation-notes').value=[$('#conversation-notes').value,text].filter(Boolean).join('\n\n');stashNotes();}});}
}
$('#confirm-remove').onclick=async()=>{const c=state.selected;if(!c||c.removedAt)return;try{await busy($('#confirm-remove'),'Removing…',async()=>{await api(`/api/candidates/${encodeURIComponent(c.id)}`,{method:'DELETE'});$('#remove-dialog').close();$('#detail-dialog').close();state.selected=null;await loadCandidates();toast('Check-in removed. Restore it from Removed check-ins if needed.');});}catch(e){$('#remove-error').textContent=e.message}};
$('#detail-dialog').addEventListener('cancel',e=>{if(interviewBusy()){e.preventDefault();toast('Stop the interview and finish saving before closing.');}});
addEventListener('beforeunload',e=>{closeMedia();if(interviewBusy()){e.preventDefault();e.returnValue='';}if(state.recording)state.recording.stop()});
setInterval(()=>{if(state.interviewer&&location.hash==='#dashboard'&&!document.hidden&&!$('#detail-dialog').open)loadCandidates()},30000);
const eventParam=new URLSearchParams(location.search).get('event');if(eventParam==='12345'){field('eventCode').value='12345';$('#event-hint').textContent='Event code received from your QR link. Join the event to continue.';}
await Promise.allSettled([readiness(),route()]);
