let active=null,releasePlayback=()=>{};
export function disposeInterviews(){if(!active){releasePlayback();releasePlayback=()=>{};}}
const seconds=ms=>{const n=Math.floor(ms/1000);return`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`};
const base64=blob=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(Error('Audio could not be read.'));r.readAsDataURL(blob)});
export const interviewBusy=()=>Boolean(active);
export function interviewPanel(c){return`<section id="interview-recorder" class="interview-recorder"><div class="interview-heading"><div><span class="section-index">INTERVIEW CAPTURE</span><h3>Be present. Keep the details.</h3><p>Record up to 20 minutes. Transcript segments save during the interview; quick notes and highlights follow when you stop.</p></div><span class="record-clock" id="interview-clock">0:00</span></div><label class="consent compact"><input type="checkbox" id="interview-voice-consent" ${!c.aiConsent||c.removedAt?'disabled':''}>Everyone present agrees to recording and sending the interview to Groq for transcription and draft notes.</label>${!c.aiConsent?'<p class="hint">This candidate has not opted in to AI processing. Use typed notes below.</p>':''}${c.removedAt?'<p class="hint">Restore this check-in to start a new interview.</p>':''}<div class="interview-buttons"><button type="button" class="primary" id="start-interview" ${!c.aiConsent||c.removedAt?'disabled':''}>Record interview</button><button type="button" class="danger hidden" id="stop-interview">Stop interview &amp; create notes</button><button type="button" class="secondary hidden" id="retry-interview">Retry pending audio</button><button type="button" class="text-button hidden" id="discard-interview">Discard unsaved audio</button></div><p id="interview-status" role="status" class="recording-status">Ready when you are. Keep this tab open while recording and saving.</p><audio id="interview-playback" class="hidden" controls></audio><p id="playback-label" class="hint hidden">Latest audio segment · playback is available in this browser session only.</p><label class="hidden" id="current-transcript-label">Saved transcript<textarea id="current-transcript" readonly rows="5"></textarea></label><div id="interview-history" class="interview-history" aria-live="polite"><p class="hint">Loading saved interviews…</p></div></section>`;}
export function mountInterviews(c,{api,post,esc,toast,onAddNotes}){
  disposeInterviews();const root=document.querySelector('#interview-recorder');if(!root)return;
  const $=s=>root.querySelector(s),start=$('#start-interview'),stop=$('#stop-interview'),status=$('#interview-status'),clock=$('#interview-clock'),retry=$('#retry-interview'),discard=$('#discard-interview');
  let history=[],viewerEmail='',objectUrl=null;releasePlayback=()=>{if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=null;};
  async function loadHistory(){try{const result=await api(`/api/candidates/${encodeURIComponent(c.id)}/interviews`);if(!root.isConnected)return;history=result.interviews;viewerEmail=result.viewerEmail;renderHistory();}catch(e){$('#interview-history').textContent=e.message;}}
  function renderHistory(){
    $('#interview-history').innerHTML=`<h4>Saved interviews <span>${history.length}</span></h4>${history.length?history.map(item=>`<article class="saved-interview"><div class="interview-meta"><strong>${esc(new Date(item.startedAt).toLocaleString())}</strong><span>${seconds(item.durationMs)} · ${esc(item.interviewerEmail)}</span><span class="badge">${item.summary?'AI draft ready':item.status==='recording'?'Partial transcript':'Transcript saved'}</span></div>${item.summary?`<div class="summary-callout">AI notes are a draft. Review the transcript; speaker identity is not automatically verified.<br>Model: ${esc(item.summary.model)}</div>${[['quickNotes','Quick notes'],['highlights','Highlights'],['followUpQuestions','Follow-up questions']].map(([key,title])=>`<h5>${title}</h5>${item.summary[key].length?`<ul class="interview-summary">${item.summary[key].map(entry=>`<li><p>${esc(entry.text)}</p><details><summary>Transcript evidence · segment ${entry.segmentSequence}</summary><blockquote>${esc(entry.evidence)}</blockquote></details></li>`).join('')}</ul>`:'<p class="hint">No items identified.</p>'}`).join('')}<button class="secondary" type="button" data-add-interview="${esc(item.id)}" ${c.removedAt?'disabled':''}>Add draft to conversation notes</button>`:item.segments.some(s=>s.transcript.trim())&&!c.removedAt&&item.interviewerEmail===viewerEmail?`<p class="hint">Your saved transcript is available even if notes generation was interrupted.</p><button class="secondary" type="button" data-finish-interview="${esc(item.id)}">Generate quick notes</button>`:'<p class="hint">No quick notes generated yet.</p>'}<details class="interview-transcript"><summary>Transcript · ${item.segments.length} saved segments</summary>${item.segments.map(s=>`<div><span class="source-chip">Segment ${s.sequence} · ${seconds(s.durationMs)}</span><p>${esc(s.transcript)}</p></div>`).join('')||'<p>No transcript saved.</p>'}</details><button class="text-button" type="button" data-download-interview="${esc(item.id)}" ${!item.segments.length?'disabled':''}>Download transcript</button><p class="detail-status" data-interview-error="${esc(item.id)}" role="alert"></p></article>`).join(''):'<p class="hint">No recorded interviews yet. Saved transcripts and highlights will appear here.</p>'}`;
    root.querySelectorAll('[data-add-interview]').forEach(button=>button.onclick=()=>{const item=history.find(i=>i.id===button.dataset.addInterview),summary=item.summary;onAddNotes([`Interview draft · ${new Date(item.startedAt).toLocaleString()}`,...[['quickNotes','Quick notes'],['highlights','Highlights'],['followUpQuestions','Follow-up questions']].flatMap(([key,title])=>summary[key].length?[title,...summary[key].map(x=>`• ${x.text} [Transcript segment ${x.segmentSequence}]`)]:[])].join('\n'));toast('Draft added below. Review and save your conversation notes.');});
    root.querySelectorAll('[data-download-interview]').forEach(button=>button.onclick=()=>{const item=history.find(i=>i.id===button.dataset.downloadInterview),text=[`TalentIQ interview · ${new Date(item.startedAt).toLocaleString()}`,`Interviewer: ${item.interviewerEmail}`,...item.segments.map(s=>`\nSegment ${s.sequence} (${seconds(s.durationMs)})\n${s.transcript}`)].join('\n'),url=URL.createObjectURL(new Blob([text],{type:'text/plain'})),link=document.createElement('a');link.href=url;link.download=`TalentIQ-interview-${item.id.slice(0,8)}.txt`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
    root.querySelectorAll('[data-finish-interview]').forEach(button=>button.onclick=async()=>{if(active){toast('Finish the current recording first.');return;}const item=history.find(i=>i.id===button.dataset.finishInterview),error=root.querySelector(`[data-interview-error="${item.id}"]`);button.disabled=true;button.textContent='Creating quick notes…';active={phase:'summary'};try{await post(`/api/interviews/${item.id}/finish`,{consent:true,segmentCount:item.segments.length});await loadHistory();toast('Quick notes ready. Review the transcript evidence.');}catch(e){error.textContent=e.message;button.disabled=false;button.textContent='Retry quick notes';}finally{active=null;}});
  }
  function resetControls(){start.disabled=!c.aiConsent||Boolean(c.removedAt);stop.classList.add('hidden');retry.classList.add('hidden');discard.classList.add('hidden');$('#interview-voice-consent').disabled=!c.aiConsent||Boolean(c.removedAt);status.classList.remove('recording');}
  function transcript(s){$('#current-transcript-label').classList.remove('hidden');$('#current-transcript').value=s.saved.map(x=>`[Segment ${x.sequence}]\n${x.transcript||'[No speech detected]'}`).join('\n\n');}
  function setError(s,e){s.error=e.message;status.textContent=`${e.message} Saved transcript segments are safe. Keep this tab open to retry unsaved audio.`;retry.classList.remove('hidden');discard.classList.remove('hidden');retry.disabled=false;}
  async function finish(s){
    if(s.finishing||s.recording||s.processing||s.pending.length||!s.lastSegmentReady)return;
    s.finishing=true;status.textContent='Transcript saved. Creating quick notes and highlights…';retry.classList.add('hidden');discard.classList.add('hidden');
    try{await post(`/api/interviews/${s.id}/finish`,{consent:true,segmentCount:s.saved.length});status.textContent='Interview saved. Quick notes and highlights are ready below.';toast('Interview notes ready for review.');}
    catch(e){status.textContent=`${e.message} Open this saved interview below to retry notes generation.`;}
    finally{active=null;resetControls();await loadHistory();}
  }
  async function pump(s){
    if(s.processing||s.error)return;s.processing=true;
    try{while(s.pending.length){const item=s.pending[0];if(item.blob.size>3e6)throw Error('An audio segment exceeded 3 MB. Retry cannot reduce its size; discard unsaved audio and use typed notes.');status.textContent=s.recording?'Recording. Saving the next transcript segment…':'Saving the remaining transcript…';const result=await post(`/api/interviews/${s.id}/segments`,{sequence:item.sequence,durationMs:item.durationMs,mime:item.blob.type,base64:await base64(item.blob),consent:true});s.saved.push({sequence:item.sequence,transcript:result.transcript});s.pending.shift();transcript(s);status.textContent=s.recording?`Recording · ${s.saved.length} transcript segments saved.`:'Transcript segments saved.';}}
    catch(e){setError(s,e);}
    finally{s.processing=false;if(!s.error)await finish(s);}
  }
  function end(s){if(!s.recording)return;s.recording=false;clearTimeout(s.cutoff);clearInterval(s.timer);clearTimeout(s.rotation);stop.disabled=true;stop.textContent='Saving interview…';status.textContent='Recording stopped. Saving the final segment…';if(s.recorder){if(s.recorder.state!=='inactive')s.recorder.stop();}else{s.lastSegmentReady=true;s.stream.getTracks().forEach(t=>t.stop());pump(s);}status.classList.remove('recording');}
  function segment(s){
    if(!s.recording)return;
    const format=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(x=>MediaRecorder.isTypeSupported(x));
    const recorder=new MediaRecorder(s.stream,{audioBitsPerSecond:48000,...(format?{mimeType:format}:{})}),chunks=[],started=Date.now();s.recorder=recorder;
    recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};
    recorder.onstop=()=>{
      clearTimeout(s.rotation);const blob=new Blob(chunks,{type:(recorder.mimeType||'audio/webm').split(';')[0]}),durationMs=Math.min(60000,Math.max(1,Date.now()-started));
      if(blob.size>=100){const item={sequence:++s.sequence,durationMs,blob};s.pending.push(item);if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(blob);$('#interview-playback').src=objectUrl;$('#interview-playback').classList.remove('hidden');$('#playback-label').classList.remove('hidden');}
      if(s.recording){try{segment(s);}catch(e){s.recording=false;clearInterval(s.timer);clearTimeout(s.cutoff);s.lastSegmentReady=true;s.stream.getTracks().forEach(t=>t.stop());setError(s,e);}}
      else{s.lastSegmentReady=true;s.stream.getTracks().forEach(t=>t.stop());}
      if(s.pending.reduce((n,item)=>n+item.blob.size,0)>12e6&&s.recording){end(s);setError(s,Error('Uploads are falling behind. Recording stopped to protect the unsaved audio.'));}
      pump(s);
    };
    recorder.onerror=()=>{end(s);setError(s,Error('The microphone recording was interrupted. Saved transcript segments are available.'));};
    // Stop/start produces a complete audio file per segment; timeslice blobs alone
    // can omit container headers and cannot reliably be transcribed independently.
    recorder.start();s.rotation=setTimeout(()=>{if(recorder.state!=='inactive')recorder.stop()},45000);
  }
  start.onclick=async()=>{
    if(active)return;
    if(!$('#interview-voice-consent').checked){status.textContent='Confirm permission from everyone present before recording.';return;}
    if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){status.textContent='This browser cannot record audio. Use a supported browser over HTTPS or type notes below.';return;}
    start.disabled=true;status.textContent='Opening microphone…';const s={id:crypto.randomUUID(),recording:false,pending:[],saved:[],sequence:0,lastSegmentReady:false};active=s;
    try{
      s.stream=await navigator.mediaDevices.getUserMedia({audio:true});await post(`/api/candidates/${encodeURIComponent(c.id)}/interviews`,{id:s.id,consent:true});
      s.recording=true;s.started=Date.now();s.timer=setInterval(()=>clock.textContent=seconds(Date.now()-s.started),1000);s.cutoff=setTimeout(()=>end(s),1200000);segment(s);
      stop.disabled=false;stop.textContent='Stop interview & create notes';stop.classList.remove('hidden');$('#interview-voice-consent').disabled=true;status.classList.add('recording');status.textContent='Recording. Transcript segments save about every 45 seconds.';
    }catch(e){clearInterval(s.timer);clearTimeout(s.cutoff);s.stream?.getTracks().forEach(t=>t.stop());active=null;resetControls();status.textContent=e.name==='NotAllowedError'?'Microphone permission was declined. Allow access in your browser or use typed notes.':e.message;}
  };
  stop.onclick=()=>{if(active)end(active)};
  retry.onclick=()=>{const s=active;if(!s)return;s.error=null;retry.disabled=true;status.textContent='Retrying pending audio…';pump(s);};
  discard.onclick=async()=>{const s=active;if(!s||s.processing)return;if(s.recording){end(s);status.textContent='Recording stopped. Choose Discard unsaved audio again after the final segment is ready.';return;}if(!s.lastSegmentReady){status.textContent='Wait for the final audio segment before discarding.';return;}if(!confirm('Discard audio that has not been saved? Saved transcript segments will remain, but unsaved audio cannot be recovered.'))return;s.pending=[];active=null;resetControls();status.textContent='Unsaved audio discarded. Saved transcript segments remain below.';await loadHistory();};
  loadHistory();
}
