import {readFileSync,writeFileSync,mkdirSync,copyFileSync,cpSync,readdirSync} from 'node:fs';
import {build} from 'esbuild';
import {fileURLToPath} from 'node:url';
const root=new URL('.',import.meta.url),read=p=>readFileSync(new URL(p,root),'utf8');
mkdirSync(new URL('dist/client/',root),{recursive:true});
for(const file of ['index.html','styles.css','fonts.css'])copyFileSync(new URL(`client/${file}`,root),new URL(`dist/client/${file}`,root));
cpSync(new URL('client/assets/',root),new URL('dist/client/assets/',root),{recursive:true});
copyFileSync(new URL('node_modules/pdfjs-dist/build/pdf.min.mjs',root),new URL('dist/client/pdf.mjs',root));
copyFileSync(new URL('node_modules/pdfjs-dist/build/pdf.worker.min.mjs',root),new URL('dist/client/pdf.worker.mjs',root));
await build({entryPoints:[fileURLToPath(new URL('client/app.js',root))],outfile:fileURLToPath(new URL('dist/client/app.js',root)),bundle:true,format:'esm',platform:'browser',target:'es2022',minify:true,legalComments:'eof'});
const html=read('dist/client/index.html');
const assets={'/':{type:'text/html; charset=utf-8',body:html},'/index.html':{type:'text/html; charset=utf-8',body:html}};
for(const file of ['styles.css','fonts.css','app.js','pdf.mjs','pdf.worker.mjs'])assets[`/${file}`]={type:file.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8',body:read(`dist/client/${file}`)};
const types={png:'image/png',ttf:'font/ttf',txt:'text/plain'};
for(const file of readdirSync(new URL('dist/client/assets/',root)))assets[`/assets/${file}`]={type:types[file.split('.').pop()]||'application/octet-stream',base64:readFileSync(new URL(`dist/client/assets/${file}`,root)).toString('base64')};
const source=read('src/worker.js').replace('/*__STATIC_ASSETS__*/',()=>`const STATIC=${JSON.stringify(assets)};`);
const result=await build({stdin:{contents:source,resolveDir:fileURLToPath(new URL('src/',root)),sourcefile:'src/worker.js',loader:'js'},bundle:true,platform:'browser',format:'esm',target:'es2022',write:false,minify:true});
mkdirSync(new URL('dist/server/',root),{recursive:true});writeFileSync(new URL('dist/server/index.js',root),result.outputFiles[0].contents);
console.log(`Built candidate and interviewer client, PDF reader, and Worker (${Object.keys(assets).length} routes).`);
